
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jaiminpatel7024/config-server-properties.git
          refresh-rate: 1
  zipkin:
    base-url: http://${VM_IP:127.0.0.1}:9411

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${VM_IP:127.0.0.1}:8761/eureka/

logging:
  level:
    org:
      springframework: INFO

zipkin:
  baseUrl: http://${VM_IP:127.0.0.1}:9411

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: refresh






